const dragonList = [
    { speciesEn: "Gaian", speciesKo: "가이안" },
    { speciesEn: "Gautling-Gon", speciesKo: "개틀링곤" },
    { speciesEn: "Girdletail Dragon", speciesKo: "거들테일" },
    { speciesEn: "Gust", speciesKo: "거스트" },
    { speciesEn: "God Dragon", speciesKo: "고대신룡" },
    { speciesEn: "God Jr", speciesKo: "고대주니어" },
    { speciesEn: "Gold Dragon", speciesKo: "골드" },
    { speciesEn: "Gold Metal", speciesKo: "골드메탈" },
    { speciesEn: "Gold Pike", speciesKo: "골드파이크" },
    { speciesEn: "Goldie", speciesKo: "골디" },
    { speciesEn: "Maniacal Power Dragon", speciesKo: "광기의 파워 드래곤" },
    { speciesEn: "Granos", speciesKo: "그라노스" },
    { speciesEn: "Gracia", speciesKo: "그라치아" },
    { speciesEn: "---Glaonae", speciesKo: "글라오네" },
    { speciesEn: "Goblin Dragon", speciesKo: "깨비곤" },
    { speciesEn: "Knight Dragon", speciesKo: "나이트" },
    { speciesEn: "Nebula", speciesKo: "네뷸라" },
    { speciesEn: "Nessie", speciesKo: "네시" },
    { speciesEn: "Nessiebig", speciesKo: "네시빅" },
    { speciesEn: "Neon Dragon", speciesKo: "네온 드래곤" },
    { speciesEn: "Nello", speciesKo: "넬로" },
    { speciesEn: "Nox", speciesKo: "녹스" },
    { speciesEn: "Non", speciesKo: "논" },
    { speciesEn: "Snow Flower Popomo", speciesKo: "눈꽃 포포모" },
    { speciesEn: "Nidhogg", speciesKo: "니드호그" },
    { speciesEn: "Ninmunia", speciesKo: "닌므니아" },
    { speciesEn: "Ninja Dragon", speciesKo: "닌자" },
    { speciesEn: "Daros", speciesKo: "다로스" },
    { speciesEn: "Darknix", speciesKo: "다크닉스" },
    { speciesEn: "Dark Angel Dragon", speciesKo: "다크 엔젤 드래곤" },
    { speciesEn: "Dark Cloud Dragon", speciesKo: "다크클라우드" },
    { speciesEn: "Demong & Gargoyle", speciesKo: "데몽과 가고일" },
    { speciesEn: "Deva", speciesKo: "데바" },
    { speciesEn: "Devared", speciesKo: "데바레드" },
    { speciesEn: "Devilgon", speciesKo: "데빌곤" },
    { speciesEn: "Dupen", speciesKo: "듀펜" },
    { speciesEn: "Dragonoid", speciesKo: "드라고노이드" },
    { speciesEn: "Dragonoid Soul", speciesKo: "드라고노이드소울" },
    { speciesEn: "Dimension Dragon", speciesKo: "디멘션" },
    { speciesEn: "Dianu", speciesKo: "디아누" },
    { speciesEn: "Diyona", speciesKo: "디요나" },
    { speciesEn: "Ragnarok", speciesKo: "라그나로크" },
    { speciesEn: "Lalux", speciesKo: "라루스" },
    { speciesEn: "Lava Dragon", speciesKo: "라바" },
    { speciesEn: "Labasalt", speciesKo: "라바솔트" },
    { speciesEn: "Light Spicy", speciesKo: "라이트스파이시" },
    { speciesEn: "Lakion", speciesKo: "라키온" },
    { speciesEn: "Rafael", speciesKo: "라파엘" },
    { speciesEn: "Rakshasa", speciesKo: "락샤사" },
    { speciesEn: "Lambgon", speciesKo: "램곤" },
    { speciesEn: "Leglien", speciesKo: "레그리언" },
    { speciesEn: "Redbull Dragon", speciesKo: "레드불" },
    { speciesEn: "Red Wyvern", speciesKo: "레드와이번" },
    { speciesEn: "Red Taabire", speciesKo: "레드타아비레" },
    { speciesEn: "Leopard Dragon", speciesKo: "레오파드" },
    { speciesEn: "Lady Dragon", speciesKo: "레이디" },
    { speciesEn: "Rekmall", speciesKo: "렉몰" },
    { speciesEn: "Lololli", speciesKo: "로롤리" },
    { speciesEn: "Rose Gold", speciesKo: "로즈골드" },
    { speciesEn: "Rugar", speciesKo: "루가르" },
    { speciesEn: "Lunera", speciesKo: "루네라" },
    { speciesEn: "Rude Ore", speciesKo: "루드오어" },
    { speciesEn: "Lumindis", speciesKo: "루민디스" },
    { speciesEn: "Lucio", speciesKo: "루시오" },
    { speciesEn: "Rupo", speciesKo: "루포" },
    { speciesEn: "Rupia", speciesKo: "루피아" },
    { speciesEn: "Libera", speciesKo: "리베라" },
    { speciesEn: "Liberte", speciesKo: "리베티" },
    { speciesEn: "Lichmond", speciesKo: "리치몬드" },
    { speciesEn: "Leaf Dragon", speciesKo: "리프" },
    { speciesEn: "Maga", speciesKo: "마가" },
    { speciesEn: "Magnello", speciesKo: "마그넬로" },
    { speciesEn: "Marino", speciesKo: "마리노" },
    { speciesEn: "Marbas", speciesKo: "마르바스" },
    { speciesEn: "Maldek", speciesKo: "말덱" },
    { speciesEn: "Maloden", speciesKo: "말로단" },
    { speciesEn: "Mud Dragon", speciesKo: "머드" },
    { speciesEn: "Mushroom Dragon", speciesKo: "머쉬룸" },
    { speciesEn: "Mushroom Knight", speciesKo: "머쉬룸나이트" },
    { speciesEn: "Mustard Hammer", speciesKo: "머스타드해머" },
    { speciesEn: "Metal Dragon", speciesKo: "메탈" },
    { speciesEn: "Mellow", speciesKo: "멜로우" },
    { speciesEn: "Hourglass Dragon", speciesKo: "모래시계 드래곤" },
    { speciesEn: "Dream Water Dragon", speciesKo: "몽수룡" },
    { speciesEn: "Minas", speciesKo: "미나스" },
    { speciesEn: "Mist Dragon", speciesKo: "미스트 드래곤" },
    { speciesEn: "Mummy Dragon", speciesKo: "미이라곤" },
    { speciesEn: "Mithra", speciesKo: "미트라" },
    { speciesEn: "Bagma", speciesKo: "바그마" },
    { speciesEn: "Vargr", speciesKo: "바르그" },
    { speciesEn: "Baal", speciesKo: "바알" },
    { speciesEn: "Rock Dragon", speciesKo: "바위" },
    { speciesEn: "Valla", speciesKo: "발라" },
    { speciesEn: "White Dragon", speciesKo: "백룡" },
    { speciesEn: "Baekho", speciesKo: "백호" },
    { speciesEn: "Hedgebat", speciesKo: "뱃도치" },
    { speciesEn: "Lightning Dragon", speciesKo: "번개고룡" },
    { speciesEn: "Vegabond", speciesKo: "베가본드" },
    { speciesEn: "Vera", speciesKo: "베라" },
    { speciesEn: "Berris", speciesKo: "베리스" },
    { speciesEn: "Vefal", speciesKo: "베팔" },
    { speciesEn: "Banshee", speciesKo: "벤시" },
    { speciesEn: "Beleth", speciesKo: "벨레드" },
    { speciesEn: "Voncias", speciesKo: "본샤스" },
    { speciesEn: "Vonsharkgon", speciesKo: "본샤크곤" },
    { speciesEn: "Bonehead", speciesKo: "본헤드" },
    { speciesEn: "Volcano Dragon", speciesKo: "볼케이노" },
    { speciesEn: "Bomber Dragon", speciesKo: "봄버" },
    { speciesEn: "Firetail", speciesKo: "불나래" },
    { speciesEn: "Black Armor", speciesKo: "블랙아머" },
    { speciesEn: "Black Armor Sword", speciesKo: "블랙아머소드" },
    { speciesEn: "Black Armor Spear", speciesKo: "블랙아머스피어" },
    { speciesEn: "Blade Dragon", speciesKo: "블레이드" },
    { speciesEn: "Blue Lightning Dragon", speciesKo: "블루라이트닝" },
    { speciesEn: "Blue Thunder", speciesKo: "블루썬더" },
    { speciesEn: "Blue Characen", speciesKo: "블루카라선" },
    { speciesEn: "Bearded Dragon", speciesKo: "비어디드래곤" },
    { speciesEn: "Frost Dragon", speciesKo: "빙하고룡" },
    { speciesEn: "Frost Blue Dragon", speciesKo: "빙하청룡" },
    { speciesEn: "Pierrot Dragon", speciesKo: "삐에로" },
    { speciesEn: "Sand Dragon", speciesKo: "샌드" },
    { speciesEn: "Shark Dragon", speciesKo: "샤크곤" },
    { speciesEn: "Sharp Tail", speciesKo: "샤프테일" },
    { speciesEn: "Siamese Dragon", speciesKo: "샴" },
    { speciesEn: "Shadow", speciesKo: "섀도우" },
    { speciesEn: "Serpent Dragon", speciesKo: "서펀트" },
    { speciesEn: "Serpent Flower", speciesKo: "서펀트플라워" },
    { speciesEn: "Seere", speciesKo: "세에레" },
    { speciesEn: "Centura", speciesKo: "센투라" },
    { speciesEn: "Solar Dragon", speciesKo: "솔라" },
    { speciesEn: "Solucanis", speciesKo: "솔루카니스" },
    { speciesEn: "Sura Dragon", speciesKo: "수라 드래곤" },
    { speciesEn: "Water Dragon", speciesKo: "수룡" },
    { speciesEn: "Surtr", speciesKo: "수르트" },
    { speciesEn: "Snow Frost Dragon", speciesKo: "스노우 빙하고룡" },
    { speciesEn: "Smart Dragon", speciesKo: "스마트" },
    { speciesEn: "Swamp Dragon", speciesKo: "스왐프" },
    { speciesEn: "Scarlet", speciesKo: "스칼렛" },
    { speciesEn: "Skelegon", speciesKo: "스켈레곤" },
    { speciesEn: "Scorpion Dragon", speciesKo: "스콜피온" },
    { speciesEn: "Skoorum", speciesKo: "스쿠룸" },
    { speciesEn: "Skink Dragon", speciesKo: "스킨크" },
    { speciesEn: "Star Ace", speciesKo: "스타에이스" },
    { speciesEn: "Stealth Dragon", speciesKo: "스텔스" },
    { speciesEn: "Stra", speciesKo: "스트라" },
    { speciesEn: "Spicy", speciesKo: "스파이시" },
    { speciesEn: "Spike Dragon", speciesKo: "스파이크" },
    { speciesEn: "Spine Dragon", speciesKo: "스파인 드래곤" },
    { speciesEn: "Splender", speciesKo: "스플렌더" },
    { speciesEn: "Slime Dragon", speciesKo: "슬라임" },
    { speciesEn: "Citael", speciesKo: "시타엘" },
    { speciesEn: "Six-leg Horn", speciesKo: "식스레그혼" },
    { speciesEn: "Agnad", speciesKo: "아그나드" },
    { speciesEn: "Anemone", speciesKo: "아네모네" },
    { speciesEn: "Artemis", speciesKo: "아르테미스" },
    { speciesEn: "Abvalle", speciesKo: "아브벨리" },
    { speciesEn: "Asti", speciesKo: "아스티" },
    { speciesEn: "Iron Dragon", speciesKo: "아이언" },
    { speciesEn: "Irondeva", speciesKo: "아이언데바" },
    { speciesEn: "Azak", speciesKo: "아자크" },
    { speciesEn: "Afrit", speciesKo: "아프리트" },
    { speciesEn: "Angra", speciesKo: "앙그라" },
    { speciesEn: "Animala", speciesKo: "애니마라" },
    { speciesEn: "Applecheek", speciesKo: "애플칙" },
    { speciesEn: "Dark God Dragon", speciesKo: "어둠의 고대신룡" },
    { speciesEn: "Dark Lightning Dragon", speciesKo: "어둠의 번개고룡" },
    { speciesEn: "Abyssedge", speciesKo: "어비스엣지" },
    { speciesEn: "Egg Dragon", speciesKo: "에그드래곤" },
    { speciesEn: "Ereboss", speciesKo: "에레보스" },
    { speciesEn: "Emerald Dragon", speciesKo: "에메랄드" },
    { speciesEn: "Eshu", speciesKo: "에슈" },
    { speciesEn: "Alien Dragon", speciesKo: "에일리언" },
    { speciesEn: "Angel Dragon", speciesKo: "엔젤" },
    { speciesEn: "Angel Jr", speciesKo: "엔젤주니어" },
    { speciesEn: "Angel Cat", speciesKo: "엔젤캣" },
    { speciesEn: "Elderly Dragon", speciesKo: "엘더 드래곤" },
    { speciesEn: "Obex", speciesKo: "오벡스" },
    { speciesEn: "Oculus", speciesKo: "오쿠러스" },
    { speciesEn: "Wind Dragon", speciesKo: "윈드" },
    { speciesEn: "Witch Dragon", speciesKo: "윗치 드래곤" },
    { speciesEn: "Wings Dragon", speciesKo: "윙스" },
    { speciesEn: "Ignis", speciesKo: "이그니스" },
    { speciesEn: "Aegis", speciesKo: "이지스" },
    { speciesEn: "Insect Dragon", speciesKo: "인섹트" },
    { speciesEn: "Insect Queen", speciesKo: "인섹트퀸" },
    { speciesEn: "Eelos", speciesKo: "일로스" },
    { speciesEn: "Ilios", speciesKo: "일리오스" },
    { speciesEn: "Jarukah", speciesKo: "자루카" },
    { speciesEn: "Zephyros", speciesKo: "제피로스" },
    { speciesEn: "Zombie Dragon", speciesKo: "좀비 드래곤" },
    { speciesEn: "Jimon", speciesKo: "즈믄" },
    { speciesEn: "Centipede Dragon", speciesKo: "G네" },
    { speciesEn: "Jima", speciesKo: "지마" },
    { speciesEn: "Underground Dragon", speciesKo: "지하땅굴" },
    { speciesEn: "Jealousy Cupid", speciesKo: "질투의 큐피트" },
    { speciesEn: "Blue Dragon", speciesKo: "청룡" },
    { speciesEn: "Blue Firetail", speciesKo: "청불나래" },
    { speciesEn: "Chungmu Haetae", speciesKo: "충무해태" },
    { speciesEn: "Characen", speciesKo: "카라선" },
    { speciesEn: "Karura", speciesKo: "카루라" },
    { speciesEn: "Khan", speciesKo: "칸" },
    { speciesEn: "Khan Marino", speciesKo: "칸마리노" },
    { speciesEn: "Catsgon", speciesKo: "캣츠곤" },
    { speciesEn: "Cobra Dragon", speciesKo: "코브라곤" },
    { speciesEn: "Kuzmara", speciesKo: "쿠즈마라" },
    { speciesEn: "Cupid", speciesKo: "큐피트" },
    { speciesEn: "Cupi Friend", speciesKo: "큐피프렌드" },
    { speciesEn: "Crested Dragon", speciesKo: "크레스티드" },
    { speciesEn: "Crookers", speciesKo: "크룩커스" },
    { speciesEn: "Cloud Dragon", speciesKo: "클라우드" },
    { speciesEn: "Taros", speciesKo: "타로스" },
    { speciesEn: "Taabire", speciesKo: "타아비레" },
    { speciesEn: "Taygeta", speciesKo: "타이게타" },
    { speciesEn: "Tycane", speciesKo: "타이케인" },
    { speciesEn: "Titan", speciesKo: "타이탄" },
    { speciesEn: "Typhoon Dragon", speciesKo: "타이푼" },
    { speciesEn: "Tattoo Dragon", speciesKo: "타투 드래곤" },
    { speciesEn: "Clockwork Dragon", speciesKo: "태엽 드래곤" },
    { speciesEn: "Teddy Dragon", speciesKo: "테디 드래곤" },
    { speciesEn: "Tediblo", speciesKo: "테디블로" },
    { speciesEn: "Totem Dragon", speciesKo: "토템" },
    { speciesEn: "T-Rex Dragon", speciesKo: "티라노 드래곤" },
    { speciesEn: "Timber Dragon", speciesKo: "팀버" },
    { speciesEn: "Python", speciesKo: "파이썬" },
    { speciesEn: "Fire Dragon", speciesKo: "파이어" },
    { speciesEn: "Power Dragon", speciesKo: "파워" },
    { speciesEn: "Party Dragon", speciesKo: "파티" },
    { speciesEn: "Pangpang", speciesKo: "팡팡" },
    { speciesEn: "Fat", speciesKo: "패트" },
    { speciesEn: "Patroa", speciesKo: "패트로아" },
    { speciesEn: "Enoki Mushroom Dragon", speciesKo: "팽이버섯" },
    { speciesEn: "Purple Lips", speciesKo: "퍼플립스" },
    { speciesEn: "Feros", speciesKo: "페로스" },
    { speciesEn: "Feyrex", speciesKo: "페이렉스" },
    { speciesEn: "Petra", speciesKo: "페트라" },
    { speciesEn: "Porta", speciesKo: "포르타" },
    { speciesEn: "Poison River", speciesKo: "포이즌 리버" },
    { speciesEn: "Popomo", speciesKo: "포포모" },
    { speciesEn: "Popon", speciesKo: "포폰" },
    { speciesEn: "Frankenstein Dragon", speciesKo: "프랑켄슈타곤" },
    { speciesEn: "Frog Dragon", speciesKo: "프로그" },
    { speciesEn: "Flower Dragon", speciesKo: "플라워" },
    { speciesEn: "Flame Dragon", speciesKo: "플레임" },
    { speciesEn: "Florea", speciesKo: "플로레" },
    { speciesEn: "Plumos", speciesKo: "플루모스" },
    { speciesEn: "Phoenix Dragon", speciesKo: "피닉스" },
    { speciesEn: "Fides", speciesKo: "피데스" },
    { speciesEn: "Pink Bell", speciesKo: "핑크벨" },
    { speciesEn: "Hallow", speciesKo: "할로우" },
    { speciesEn: "Haetae", speciesKo: "해태" },
    { speciesEn: "Hurricane Dragon", speciesKo: "허리케인" },
    { speciesEn: "Henes", speciesKo: "헤네스" },
    { speciesEn: "Hercules Dragon", speciesKo: "헤라클레스곤" },
    { speciesEn: "Haze", speciesKo: "헤이즈" },
    { speciesEn: "Hell Dragon", speciesKo: "헬" },
    { speciesEn: "Hela", speciesKo: "헬라" },
    { speciesEn: "Hyeonmu", speciesKo: "현무" },
    { speciesEn: "Fire Ghost Dragon", speciesKo: "화귀 드래곤" },
    { speciesEn: "White Gold", speciesKo: "화이트골드" },
    { speciesEn: "White Thunder Dragon", speciesKo: "화이트썬더" },
    { speciesEn: "Gold Applecheek", speciesKo: "황금 애플칙" },
    { speciesEn: "Black Dragon", speciesKo: "흑룡" },
    { speciesEn: "Hydragon", speciesKo: "히드라곤" }
];

const dragonTraits = [
    { traitEn: "Fearful", traitKo: "겁이 많은" },
    { traitEn: "Noble", traitKo: "고귀한" },
    { traitEn: "Adamant", traitKo: "고집있는" },
    { traitEn: "Lunatic", traitKo: "광적인" },
    { traitEn: "Elegant", traitKo: "기품있는" },
    { traitEn: "Neat", traitKo: "깨끗한" },
    { traitEn: "Introvert", traitKo: "내향적인" },
    { traitEn: "Quiet", traitKo: "냉정한" },
    { traitEn: "Hardy", traitKo: "노력하는" },
    { traitEn: "Quick Witted", traitKo: "눈치빠른" },
    { traitEn: "Bold", traitKo: "대담한" },
    { traitEn: "Rash", traitKo: "덜렁대는" },
    { traitEn: "Smart", traitKo: "똑똑한" },
    { traitEn: "Immersed", traitKo: "몰입하는" },
    { traitEn: "Unknown", traitKo: "미지의" },
    { traitEn: "Quirky", traitKo: "변덕쟁이" },
    // { traitEn: "-", traitKo: "보름달의" },
    { traitEn: "Lousy", traitKo: "부족한" },
    { traitEn: "Sociable", traitKo: "사교적인" },
    { traitEn: "Wild", traitKo: "사나운" },
    { traitEn: "Lovely", traitKo: "사랑스러운" },
    { traitEn: "Distracted", traitKo: "산만한" },
    { traitEn: "Clumsy", traitKo: "서투른" },
    { traitEn: "Hasty", traitKo: "성급한" },
    { traitEn: "Serious", traitKo: "성실한" },
    { traitEn: "Timid", traitKo: "소극적인" },
    { traitEn: "Bashful", traitKo: "수줍은" },
    { traitEn: "Pure", traitKo: "순수한" },
    { traitEn: "Mystic", traitKo: "신비의" },
    { traitEn: "Careful", traitKo: "신중한" },
    { traitEn: "Charming", traitKo: "애교많은" },
    { traitEn: "Arrogant", traitKo: "오만한" },
    { traitEn: "Docile", traitKo: "온순한" },
    { traitEn: "Perfectionist", traitKo: "완벽주의자" },
    { traitEn: "Lonely", traitKo: "외로워하는" },
    { traitEn: "Brave", traitKo: "용감한" },
    { traitEn: "Capable", traitKo: "유능한" },
    { traitEn: "Baleful", traitKo: "재앙의" },
    { traitEn: "Meticulous", traitKo: "정확한" },
    { traitEn: "Silent", traitKo: "조용한" },
    { traitEn: "Calm", traitKo: "차분한" },
    { traitEn: "Naive", traitKo: "천진난만한" },
    { traitEn: "Lax", traitKo: "촐랑대는" },
    { traitEn: "Dull", traitKo: "평범한" },
    // { traitEn: "-", traitKo: "푸른달의" },
    { traitEn: "Classy", traitKo: "품위있는" },
    { traitEn: "Curious", traitKo: "호기심많은" }
];

const traitColors = {
    "겁이 많은": "#59C1BD",
    "고귀한": "#F9F9F9",
    "고집있는": "#537FE7",
    "광적인": "#FF78C4",
    "기품있는": "#FFC107",
    "깨끗한": "#FFC107",
    "내향적인": "#DD2C00",
    "냉정한": "#537FE7",
    "노력하는": "#393E46",
    "눈치빠른": "#81B214",
    "대담한": "#59C1BD",
    "덜렁대는": "#F58634",
    "똑똑한": "#81B214",
    "몰입하는": "#DD2C00",
    "미지의": "#7C73C0",
    "변덕쟁이": "#7C73C0",
    "부족한": "#393E46",
    "사교적인": "#FF78C4",
    "사나운": "#393E46",
    "사랑스러운": "#FF78C4",
    "산만한": "#59C1BD",
    "서투른": "#7C73C0",
    "성급한": "#F58634",
    "성실한": "#537FE7",
    "소극적인": "#F58634",
    "수줍은": "#B9B4C7",
    "순수한": "#F9F9F9",
    "신비의": "#59C1BD",
    "신중한": "#393E46",
    "애교많은": "#FFC107",
    "오만한": "#DD2C00",
    "온순한": "#81B214",
    "완벽주의자": "#F9F9F9",
    "외로워하는": "#7C73C0",
    "용감한": "#DD2C00",
    "유능한": "#537FE7",
    "재앙의": "#393E46",
    "정확한": "#393E46",
    "조용한": "#393E46",
    "차분한": "#F58634",
    "천진난만한": "#FFC107",
    "촐랑대는": "#FF78C4",
    "평범한": "#537FE7",
    "품위있는": "#F9F9F9",
    "호기심많은": "#81B214",
};
